easy_admin:
    entities:
        User:
          class: App\Entity\User
          form:
              fields:
                  - {property: 'username'}
                  - {property: 'email'}
                  - {property: 'password'}
                  - {property: 'isEnable'}
#                  - {property: 'roles'}
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
